FROM python:3.11-slim
WORKDIR /app
COPY ingestion/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ingestion/ais/signal_analyser.py .
CMD ["python", "signal_analyser.py"]